---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u3688835/public_html/sidadik/
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - /bin/cp crud_web.php $DEPLOYPATH
    - /bin/cp beranda.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R dist $DEPLOYPATH
    - /bin/cp -R temp $DEPLOYPATH
    - /bin/cp -R user $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH